// REVIEW: possible technical term remaining
// Central mock data for 5 consultations.
// Houses are 1..12. Planet abbreviations: Su Mo Ma Me Ju Ve Sa Ra Ke. Lg = Lagna marker.

function makeLog(rows) {
  const base = new Date('2026-04-28T09:14:32');
  return rows.map((r, i) => {
    const t = new Date(base.getTime() + i * 7400 + (i % 3) * 1700);
    const hh = String(t.getHours()).padStart(2, '0');
    const mm = String(t.getMinutes()).padStart(2, '0');
    const ss = String(t.getSeconds()).padStart(2, '0');
    return { time: `${hh}:${mm}:${ss}`, type: r[0], message: r[1] };
  });
}

export const MOCK_DATA = [
  {
    id: 'ASTRO-2026-001',
    name: 'Arjun Sharma',
    email: 'arjun.sharma@email.com',
    receivedAt: '2026-04-28 09:14:32',
    waitingMin: 14,
    status: 'HIL_PENDING',
    dob: '15 July 1990',
    tob: '06:32 AM',
    pob: 'Mumbai, Maharashtra',
    coordinates: '18.97°N 72.82°E',
    timezone: 'UTC+5:30',
    ayanamsa: 'Lahiri',
    lagna: 'Cancer',
    rasiChart: {
      1: ['Lg', 'Mo'],
      4: ['Ma'],
      5: ['Ra'],
      7: ['Ve'],
      10: ['Ju', 'Su'],
      11: ['Ke', 'Sa'],
      12: ['Me'],
    },
    activeMahadasha: 'Saturn',
    activeAntardasha: 'Mercury',
    dashaEnds: 'March 2028',
    yogas: ['Raj Yoga', 'Gajakesari Yoga'],
    doshas: ['Sade Sati', 'Mangal Dosha'],
    concerns: ['Career', 'Finance', 'Health'],
    overallConfidence: 72,
    processingTime: '00:02:34',
    interpretations: {
      career: { insight: 'Saturn–Mercury dasha favours methodical career building. Promotion window opens Aug–Nov 2026 if you stay in current role; a lateral move now would forfeit Jupiter\'s 10th-house dignity.', confidence: 85, planet: 'Saturn', flagged: false },
      finance: { insight: 'Jupiter in 10th from Lagna activates 2nd-house wealth. Long-term investments preferred over speculation. Avoid major capital lock-ups during Mercury sub-period retrogrades.', confidence: 78, planet: 'Jupiter', flagged: false },
      health: { insight: 'Saturn currently transiting natal 8th house — chronic stress markers indicated. Lower back and digestive system require attention. Recommend medical screening within 90 days.', confidence: 45, planet: 'Saturn', flagged: true, flagReason: 'Saturn transiting 8th house — sensitive health prediction. Confidence below 50% threshold for autonomous clearance.' },
      relations: { insight: 'Venus in 7th brings stable partnership energy through 2027. Existing relationships strengthen; for unmarried, Nov 2026 carries strong matrimonial yoga.', confidence: 81, planet: 'Venus', flagged: false },
      muhurta: { insight: 'Best dates for new ventures: 12 May, 27 June, 14 September 2026. Avoid Tuesdays in July (Mangal Dosha activation). Pradosh Kaal favourable.', confidence: 88, planet: 'Jupiter', flagged: false },
    },
    hilStatus: 'PENDING',
    remedy: 'Recite Hanuman Chalisa daily at sunrise. Donate black sesame seeds on Saturdays. Wear blue sapphire only after trial period of 3 days.',
    reportReady: false,
    agentLog: makeLog([
      ['INFO',      'New Jataka received.'],
      ['INFO',      'Parsing birth data: DOB=15 July 1990, TOB=06:32 AM, POB=Mumbai, Maharashtra.'],
      ['INFO',      'Geocoding birth location Mumbai, Maharashtra...'],
      ['SUCCESS',   'Coordinates locked: 18.97°N 72.82°E UTC+5:30. Lahiri Ayanamsa applied.'],
      ['INFO',      'Planetary computation initialised. Calculating planetary positions for 15 July 1990 06:32 AM IST...'],
      ['SUCCESS',   'Lagna confirmed: Cancer. Moon in 1st house, strong positional strength (Shadbala 6.4/8).'],
      ['SUCCESS',   'Raj Yoga detected — Jupiter conjunct Sun in 10th house from Lagna. Confidence: HIGH.'],
      ['SUCCESS',   'Gajakesari Yoga detected — Jupiter–Moon kendra relationship. Confidence: HIGH.'],
      ['WARNING',   'Sade Sati ongoing — Saturn in 12th from natal Moon. Phase: peak. Duration remaining ~22 months.'],
      ['WARNING',   'Mangal Dosha confirmed — Mars in 4th house. Strength: moderate.'],
      ['INFO',      'Calculating Vimshottari Dasha. Active: Saturn Mahadasha → Mercury Antardasha. Ends Mar 2028.'],
      ['INFO',      'Generating interpretation for concern: Career.'],
      ['SUCCESS',   'Career insight cleared — confidence 85%.'],
      ['INFO',      'Generating interpretation for concern: Finance.'],
      ['SUCCESS',   'Finance insight cleared — confidence 78%.'],
      ['INFO',      'Generating interpretation for concern: Health.'],
      ['FLAGGED',   'Saturn transiting natal 8th house. Health prediction sensitivity threshold exceeded.'],
      ['ROUTED',    'Health section routed to Drishti Board.'],
      ['SUCCESS',   'Relations insight cleared — confidence 81%.'],
      ['SUCCESS',   'Muhurta calculation complete — confidence 88%.'],
      ['INFO',      'Compiling remedy recommendations.'],
      ['INFO',      '4 of 5 sections cleared. 1 awaiting Jyotishi.'],
    ]),
  },
  {
    id: 'ASTRO-2026-002',
    name: 'Priya Iyer',
    email: 'priya.iyer@email.com',
    receivedAt: '2026-04-28 09:42:08',
    waitingMin: 0,
    status: 'PROCESSING',
    dob: '03 February 1988',
    tob: '11:48 PM',
    pob: 'Chennai, Tamil Nadu',
    coordinates: '13.08°N 80.27°E',
    timezone: 'UTC+5:30',
    ayanamsa: 'Lahiri',
    lagna: 'Libra',
    rasiChart: {
      1: ['Lg'],
      2: ['Ve'],
      3: ['Su', 'Me'],
      4: ['Ma'],
      6: ['Ra'],
      9: ['Ju'],
      10: ['Mo'],
      12: ['Sa', 'Ke'],
    },
    activeMahadasha: 'Venus',
    activeAntardasha: 'Sun',
    dashaEnds: 'February 2027',
    yogas: ['Dhana Yoga'],
    doshas: [],
    concerns: ['Marriage', 'Career'],
    overallConfidence: 81,
    processingTime: '00:01:12',
    interpretations: {
      career: { insight: 'Venus dasha currently elevating creative and aesthetic professions. Mercury in 3rd house supports communication-led roles.', confidence: 84, planet: 'Venus', flagged: false },
      finance: { insight: 'Dhana Yoga active through 2027. Jupiter in 9th supports wealth via mentors and overseas connections.', confidence: 80, planet: 'Jupiter', flagged: false },
      health: { insight: 'No major affliction. Maintain regular Pranayama; minor kidney sensitivity indicated.', confidence: 76, planet: 'Venus', flagged: false },
      relations: { insight: 'Marriage prospects strong from Sep 2026. Partner likely from professional or academic circle. Compatibility scoring favourable.', confidence: 83, planet: 'Venus', flagged: false },
      muhurta: { insight: 'Engagement muhurta auspicious: 6 Oct, 19 Nov 2026. Avoid Mercury retrograde windows.', confidence: 82, planet: 'Jupiter', flagged: false },
    },
    hilStatus: 'NONE',
    remedy: 'Friday Lakshmi pooja. White cloth donation at temple. Sphatik mala for daily mantra japa.',
    reportReady: false,
    agentLog: makeLog([
      ['INFO',    'Inbound consultation received.'],
      ['INFO',    'Parsing birth data: DOB=03 Feb 1988, TOB=11:48 PM, POB=Chennai.'],
      ['SUCCESS', 'Coordinates locked: 13.08°N 80.27°E. Lahiri Ayanamsa applied.'],
      ['INFO',    'Calculating planetary positions...'],
      ['SUCCESS', 'Lagna confirmed: Libra. No malefic in 1st house.'],
      ['SUCCESS', 'Dhana Yoga detected — 2nd lord Mars in own sign aspecting 11th.'],
      ['INFO',    'Vimshottari: Venus Mahadasha → Sun Antardasha. Ends Feb 2027.'],
      ['INFO',    'Generating interpretations for Marriage and Career...'],
    ]),
  },
  {
    id: 'ASTRO-2026-003',
    name: 'Rahul Mehta',
    email: 'rahul.mehta@email.com',
    receivedAt: '2026-04-28 08:51:17',
    waitingMin: 38,
    status: 'HIL_PENDING',
    dob: '22 November 1979',
    tob: '03:18 PM',
    pob: 'Ahmedabad, Gujarat',
    coordinates: '23.02°N 72.57°E',
    timezone: 'UTC+5:30',
    ayanamsa: 'Lahiri',
    lagna: 'Pisces',
    rasiChart: {
      1: ['Lg', 'Ju'],
      3: ['Ke'],
      4: ['Sa'],
      6: ['Ma'],
      7: ['Su', 'Me', 'Ve'],
      9: ['Ra'],
      11: ['Mo'],
    },
    activeMahadasha: 'Rahu',
    activeAntardasha: 'Jupiter',
    dashaEnds: 'July 2029',
    yogas: ['Hamsa Yoga', 'Budha-Aditya Yoga'],
    doshas: ['Kala Sarpa Dosha'],
    concerns: ['Litigation', 'Health', 'Finance'],
    overallConfidence: 64,
    processingTime: '00:03:41',
    interpretations: {
      career: { insight: 'Rahu–Jupiter dasha amplifies foreign or unconventional career arcs. Existing leadership role stable through 2027.', confidence: 76, planet: 'Rahu', flagged: false },
      finance: { insight: 'Significant capital decision indicated within 6 months. Jupiter in Lagna provides protection but Rahu adds speculative pull — restraint advised.', confidence: 58, planet: 'Jupiter', flagged: true, flagReason: 'Kala Sarpa Dosha active. Financial prediction with material consequence — Jyotishi review mandatory.' },
      health: { insight: 'Mars in 6th house supports general vitality. Watch for inflammatory conditions during Apr–May 2027.', confidence: 71, planet: 'Mars', flagged: false },
      relations: { insight: '7th house stellium (Sun, Mercury, Venus) keeps partnership central. Communication breakthroughs expected.', confidence: 79, planet: 'Venus', flagged: false },
      muhurta: { insight: 'Pending litigation: best filing windows 8 May, 21 June 2026. Court proceedings favour calm presentation.', confidence: 42, planet: 'Saturn', flagged: true, flagReason: 'Litigation timing prediction crosses legal-impact threshold. Confidence below 50%.' },
    },
    hilStatus: 'PENDING',
    remedy: 'Naga pratishtha at Nageshwar Jyotirlinga. Silver Naga idol gifted to temple. Rahu shanti homa once.',
    reportReady: false,
    agentLog: makeLog([
      ['INFO',      'Inbound consultation received.'],
      ['SUCCESS',   'Coordinates locked: 23.02°N 72.57°E. Lahiri Ayanamsa applied.'],
      ['SUCCESS',   'Lagna confirmed: Pisces. Jupiter in own sign in 1st house — strong.'],
      ['SUCCESS',   'Hamsa Yoga detected — Jupiter exalted in Lagna kendra.'],
      ['SUCCESS',   'Budha-Aditya Yoga detected — Mercury and Sun conjunct in 7th house.'],
      ['WARNING',   'Kala Sarpa Dosha confirmed — all planets between Rahu (9H) and Ketu (3H).'],
      ['INFO',      'Vimshottari: Rahu Mahadasha → Jupiter Antardasha. Ends Jul 2029.'],
      ['FLAGGED',   'Finance interpretation involves material capital decision. Confidence 58% — below auto-clear threshold.'],
      ['FLAGGED',   'Litigation muhurta below 50% confidence under Kala Sarpa influence.'],
      ['ROUTED',    '2 sections routed to Drishti Board.'],
      ['INFO',      'Career, Health, Relations sections cleared.'],
    ]),
  },
  {
    id: 'ASTRO-2026-004',
    name: 'Nisha Reddy',
    email: 'nisha.reddy@email.com',
    receivedAt: '2026-04-28 07:22:54',
    waitingMin: 0,
    status: 'INTERPRETING',
    dob: '09 September 1995',
    tob: '04:55 AM',
    pob: 'Hyderabad, Telangana',
    coordinates: '17.38°N 78.49°E',
    timezone: 'UTC+5:30',
    ayanamsa: 'Lahiri',
    lagna: 'Leo',
    rasiChart: {
      1: ['Lg', 'Su'],
      2: ['Me'],
      3: ['Ve'],
      4: ['Ma', 'Ke'],
      7: ['Mo'],
      9: ['Ju'],
      10: ['Ra'],
      11: ['Sa'],
    },
    activeMahadasha: 'Jupiter',
    activeAntardasha: 'Saturn',
    dashaEnds: 'November 2031',
    yogas: ['Sasa Yoga', 'Chandra Mangal Yoga'],
    doshas: [],
    concerns: ['Higher Studies', 'Career'],
    overallConfidence: 86,
    processingTime: '00:02:08',
    interpretations: {
      career: { insight: 'Jupiter–Saturn dasha favours academic and research-oriented paths. PhD or specialist track strongly indicated.', confidence: 89, planet: 'Jupiter', flagged: false },
      finance: { insight: 'Saturn in 11th house ensures steady income growth. Scholarships and grants available through Mar 2027.', confidence: 87, planet: 'Saturn', flagged: false },
      health: { insight: 'Sun in Lagna provides robust constitution. Maintain eye health; reduce screen time during Mercury sub-periods.', confidence: 84, planet: 'Sun', flagged: false },
      relations: { insight: 'Moon in 7th brings emotionally rich partnerships. Long-distance connection forming late 2026.', confidence: 82, planet: 'Moon', flagged: false },
      muhurta: { insight: 'Application windows for foreign universities: 17 Aug, 4 Oct 2026. Visa interview muhurta: morning hours, Thursdays.', confidence: 88, planet: 'Jupiter', flagged: false },
    },
    hilStatus: 'NONE',
    remedy: 'Surya Namaskar at sunrise. Yellow sapphire after consultation with Jyotishi. Ganesha mantra before exams.',
    reportReady: false,
    agentLog: makeLog([
      ['INFO',    'Inbound consultation received.'],
      ['SUCCESS', 'Coordinates locked: 17.38°N 78.49°E. Lahiri Ayanamsa applied.'],
      ['SUCCESS', 'Lagna confirmed: Leo. Sun in own sign in 1st house — very strong.'],
      ['SUCCESS', 'Sasa Yoga detected — Saturn in own sign in kendra from Moon.'],
      ['SUCCESS', 'Chandra Mangal Yoga — Moon and Mars mutual aspect.'],
      ['INFO',    'Vimshottari: Jupiter Mahadasha → Saturn Antardasha. Ends Nov 2031.'],
      ['INFO',    'Generating interpretations for Higher Studies and Career...'],
      ['SUCCESS', 'Career interpretation cleared — confidence 89%.'],
      ['INFO',    'Compiling remedy recommendations...'],
    ]),
  },
  {
    id: 'ASTRO-2026-005',
    name: 'Vikram Singh',
    email: 'vikram.singh@email.com',
    receivedAt: '2026-04-27 18:09:41',
    waitingMin: 0,
    status: 'COMPLETE',
    dob: '28 May 1972',
    tob: '09:14 AM',
    pob: 'Jaipur, Rajasthan',
    coordinates: '26.91°N 75.79°E',
    timezone: 'UTC+5:30',
    ayanamsa: 'Lahiri',
    lagna: 'Gemini',
    rasiChart: {
      1: ['Lg', 'Me'],
      3: ['Mo'],
      5: ['Ra'],
      6: ['Sa'],
      8: ['Ma'],
      10: ['Ju', 'Ve'],
      11: ['Ke', 'Su'],
    },
    activeMahadasha: 'Mercury',
    activeAntardasha: 'Venus',
    dashaEnds: 'June 2030',
    yogas: ['Bhadra Yoga', 'Lakshmi Yoga'],
    doshas: ['Mangal Dosha'],
    concerns: ['Business', 'Property', 'Children'],
    overallConfidence: 79,
    processingTime: '00:02:53',
    interpretations: {
      career: { insight: 'Mercury–Venus dasha excellent for business expansion and new partnerships. Q3 2026 favourable for product launch.', confidence: 82, planet: 'Mercury', flagged: false },
      finance: { insight: 'Lakshmi Yoga active. Property acquisition window Jun–Sep 2026. Land or commercial real estate preferred over residential.', confidence: 81, planet: 'Venus', flagged: false },
      health: { insight: 'Mars in 8th house — exercise caution during travel. Joint health needs preventive care.', confidence: 73, planet: 'Mars', flagged: false },
      relations: { insight: 'Children\'s career trajectory strong; eldest entering pivotal academic phase.', confidence: 78, planet: 'Jupiter', flagged: false },
      muhurta: { insight: 'Property registration auspicious: 14 Jun, 22 Aug 2026. Business agreement signing best Wed/Thu mornings.', confidence: 80, planet: 'Mercury', flagged: false },
    },
    hilStatus: 'APPROVED',
    remedy: 'Mangal shanti puja annually. Coral ring on Tuesday in gold. Hanuman Chalisa Tuesdays/Saturdays.',
    reportReady: true,
    agentLog: makeLog([
      ['INFO',    'Inbound consultation received.'],
      ['SUCCESS', 'Coordinates locked: 26.91°N 75.79°E.'],
      ['SUCCESS', 'Lagna confirmed: Gemini. Mercury in own sign in 1st house.'],
      ['SUCCESS', 'Bhadra Yoga detected — Mercury in kendra in own sign.'],
      ['SUCCESS', 'Lakshmi Yoga — 9th lord Saturn well-placed; Venus in 10th.'],
      ['WARNING', 'Mangal Dosha — Mars in 8th house. Mitigation factors present.'],
      ['INFO',    'All 5 interpretations generated.'],
      ['SUCCESS', 'All sections cleared.'],
      ['SUCCESS', 'Review approved by Jyotishi.'],
      ['SUCCESS', 'Final report compiled and delivered. Patrika delivered.'],
    ]),
  },
];

export const STATUS_META = {
  PROCESSING:   { label: 'Processing',   tone: 'blue',    bg: 'var(--blue-50)',    fg: '#1D4ED8' },
  INTERPRETING: { label: 'Interpreting', tone: 'indigo',  bg: 'var(--indigo-50)',  fg: 'var(--indigo-700)' },
  HIL_PENDING:  { label: 'Drishti Pending',  tone: 'amber',   bg: 'var(--amber-50)',   fg: 'var(--amber-700)' },
  COMPLETE:     { label: 'Complete',     tone: 'emerald', bg: 'var(--emerald-50)', fg: 'var(--emerald-700)' },
};

export const JATAKA_REPORTS = {
  'ASTRO-2026-001': {
    daily: [
      {
        date: '2026-04-27',
        panchang: { tithi: 'Navami', nakshatra: 'Krittika', yoga: 'Shubha', karana: 'Balava', vara: 'Monday' },
        moonSign: 'Taurus',
        rahuKaal: '07:30 AM – 09:00 AM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Cream',
        luckyNumber: 8,
        luckyDirection: 'West',
        dashaInsight: 'Saturn–Mercury opens the week with a methodical tone. Best for paperwork and structured planning.',
        transitAlert: 'Moon transiting your 11th house — gains through colleagues likely.',
        careerTip: 'Begin documentation work early. Avoid pitches before noon under Sade Sati pressure.',
        financeTip: 'Review contracts; defer signing until Wednesday.',
        healthTip: 'Lower back stiffness possible — gentle stretching advised.',
        mantra: 'Om Sham Shanaischaraya Namah',
        auspiciousFor: ['Planning', 'Documentation', 'Reviewing contracts'],
        avoidToday: ['Speculation', 'Heated debates'],
      },
      {
        date: '2026-04-28',
        panchang: { tithi: 'Dashami', nakshatra: 'Rohini', yoga: 'Siddha', karana: 'Bava', vara: 'Tuesday' },
        moonSign: 'Taurus',
        rahuKaal: '03:00 PM – 04:30 PM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'White',
        luckyNumber: 2,
        luckyDirection: 'North-West',
        dashaInsight: 'Saturn–Mercury favours focused administrative work. Avoid impulsive decisions before noon.',
        transitAlert: 'Moon in Rohini brings creative momentum and an aesthetic eye for detail.',
        careerTip: 'Strong day for presentations and team communication.',
        financeTip: 'Avoid large transactions during Rahu Kaal window.',
        healthTip: 'Pitta elevated under Mangal Dosha — favour cooling foods, avoid confrontation.',
        mantra: 'Om Som Somaya Namah',
        auspiciousFor: ['Learning', 'Travel planning', 'Creative work'],
        avoidToday: ['Confrontations', 'Major purchases'],
      },
      {
        date: '2026-04-29',
        panchang: { tithi: 'Ekadashi', nakshatra: 'Mrigashira', yoga: 'Sadhya', karana: 'Vanija', vara: 'Wednesday' },
        moonSign: 'Taurus',
        rahuKaal: '12:00 PM – 01:30 PM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Green',
        luckyNumber: 5,
        luckyDirection: 'North',
        dashaInsight: 'Mercury Antardasha peaks today — communication and analysis sharpened.',
        transitAlert: 'Mercury in own house aspects Lagna — clarity in decision-making.',
        careerTip: 'Best day this week for negotiations and key conversations.',
        financeTip: 'Jupiter in 10th supports long-term wealth structuring decisions.',
        healthTip: 'Steady; maintain hydration through the afternoon.',
        mantra: 'Om Bram Brim Braum Sah Budhaya Namah',
        auspiciousFor: ['Negotiation', 'Signing', 'Public speaking'],
        avoidToday: ['Gossip', 'Spreading thin across tasks'],
      },
      {
        date: '2026-04-30',
        panchang: { tithi: 'Dwadashi', nakshatra: 'Ardra', yoga: 'Shubha', karana: 'Vishti', vara: 'Thursday' },
        moonSign: 'Gemini',
        rahuKaal: '01:30 PM – 03:00 PM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Yellow',
        luckyNumber: 3,
        luckyDirection: 'North-East',
        dashaInsight: 'Jupiter aspects natal Moon — emotional balance and elder support available.',
        transitAlert: 'Vishti karana — avoid initiating new ventures; consolidate ongoing.',
        careerTip: 'Promotion conversations favoured if begun before 11 AM.',
        financeTip: 'Auspicious to set up SIPs or recurring deposits today.',
        healthTip: 'Sun in 10th supports vitality — short morning walk recommended.',
        mantra: 'Om Gram Grim Graum Sah Gurave Namah',
        auspiciousFor: ['Mentor meetings', 'Higher learning', 'Charity'],
        avoidToday: ['New launches', 'Risky travel'],
      },
      {
        date: '2026-05-01',
        panchang: { tithi: 'Trayodashi', nakshatra: 'Punarvasu', yoga: 'Shukla', karana: 'Bava', vara: 'Friday' },
        moonSign: 'Gemini',
        rahuKaal: '10:30 AM – 12:00 PM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Pink',
        luckyNumber: 6,
        luckyDirection: 'South-East',
        dashaInsight: 'Venus in 7th brings warmth in partnerships — both personal and professional.',
        transitAlert: 'Venus exalted aspect favours creative and aesthetic work.',
        careerTip: 'Client and stakeholder calls land well today.',
        financeTip: 'Lakshmi-friendly day — small auspicious purchases acceptable.',
        healthTip: 'Reproductive system needs gentle attention; rest if fatigued.',
        mantra: 'Om Dram Drim Draum Sah Shukraya Namah',
        auspiciousFor: ['Partnerships', 'Aesthetic purchases', 'Lakshmi pooja'],
        avoidToday: ['Heavy disputes', 'Excess indulgence'],
      },
      {
        date: '2026-05-02',
        panchang: { tithi: 'Chaturdashi', nakshatra: 'Pushya', yoga: 'Brahma', karana: 'Vanija', vara: 'Saturday' },
        moonSign: 'Cancer',
        rahuKaal: '09:00 AM – 10:30 AM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Blue',
        luckyNumber: 8,
        luckyDirection: 'West',
        dashaInsight: 'Saturn day reinforces the Mahadasha tone — reflection and discipline.',
        transitAlert: 'Pushya nakshatra — most auspicious nakshatra for new commitments.',
        careerTip: 'Begin a long-term project; today\'s start carries Saturnine longevity.',
        financeTip: 'Donate sesame seeds or iron — Saturn remedy alignment.',
        healthTip: 'Sade Sati peak — avoid overcommitment; early sleep advised.',
        mantra: 'Om Sham Shanaischaraya Namah',
        auspiciousFor: ['Beginnings under Pushya', 'Saturn remedies', 'Reflection'],
        avoidToday: ['Late-night travel', 'Overexertion'],
      },
      {
        date: '2026-05-03',
        panchang: { tithi: 'Purnima', nakshatra: 'Ashlesha', yoga: 'Indra', karana: 'Bava', vara: 'Sunday' },
        moonSign: 'Cancer',
        rahuKaal: '04:30 PM – 06:00 PM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Orange',
        luckyNumber: 1,
        luckyDirection: 'East',
        dashaInsight: 'Full Moon in your Lagna sign — emotional clarity and reset point of the week.',
        transitAlert: 'Purnima brings amplified results of the week\'s actions.',
        careerTip: 'Reflect on weekly progress; journal observations for Monday.',
        financeTip: 'Avoid impulse spending around the Full Moon peak.',
        healthTip: 'Hydrate well; Moon in Lagna heightens emotional sensitivity.',
        mantra: 'Om Hram Hrim Hraum Sah Suryaya Namah',
        auspiciousFor: ['Family time', 'Spiritual practice', 'Closure of cycles'],
        avoidToday: ['Sharp arguments', 'Decisions while emotional'],
      },
    ],
    weekly: [
      {
        weekStart: '2026-04-06',
        weekEnd: '2026-04-12',
        overallTone: 'Mixed',
        keyTransit: 'Mars retrograde shadow ends — momentum gradually returns through the week.',
        dashaInsight: 'Saturn–Mercury continues its administrative emphasis. Slow but steady.',
        career: 'First half quiet; Thursday onward picks up. Avoid escalations on Tuesday.',
        finance: 'Hold large outflows; review fixed expenses.',
        health: 'Sade Sati pressure noticeable mid-week — extra rest helps.',
        relations: 'Family communication needs patience; weekend brings warmth.',
        bestDays: ['Thursday', 'Saturday'],
        avoidDays: ['Tuesday'],
        muhurta: 'Best window for new beginnings: Saturday 10:00–11:30 AM.',
      },
      {
        weekStart: '2026-04-13',
        weekEnd: '2026-04-19',
        overallTone: 'Favourable',
        keyTransit: 'Jupiter aspects natal Moon mid-week — clarity and elder support.',
        dashaInsight: 'Mercury sub-period sharpens analytical work. Strong week for documentation.',
        career: 'Visibility week. Wednesday best for proposals; Friday seals decisions.',
        finance: 'Long-term investment review favoured. Avoid speculation.',
        health: 'Stable; light pranayama keeps Mangal Dosha calm.',
        relations: 'Romantic Venus aspect on Friday — quality time advised.',
        bestDays: ['Wednesday', 'Friday'],
        avoidDays: ['Monday'],
        muhurta: 'New ventures: Wednesday 11:30 AM – 12:30 PM.',
      },
      {
        weekStart: '2026-04-20',
        weekEnd: '2026-04-26',
        overallTone: 'Challenging',
        keyTransit: 'Saturn intensifies in 8th from natal Moon — Sade Sati peak phase.',
        dashaInsight: 'Saturn–Mercury under pressure; methodical caution advised.',
        career: 'Defer high-stakes presentations; consolidate existing work.',
        finance: 'No large commitments. Emergency reserve check recommended.',
        health: 'Lower back, digestion, sleep — all need attention.',
        relations: 'Listen more than speak; partner may need space.',
        bestDays: ['Saturday'],
        avoidDays: ['Tuesday', 'Wednesday'],
        muhurta: 'Avoid muhurta-dependent work this week if possible.',
      },
      {
        weekStart: '2026-04-27',
        weekEnd: '2026-05-03',
        overallTone: 'Favourable',
        keyTransit: 'Jupiter aspects natal Moon mid-week — clarity and optimism.',
        dashaInsight: 'Saturn–Mercury week favours methodical progress. Wednesday is peak.',
        career: 'Strong week for leadership visibility. Thursday best for key decisions.',
        finance: 'Avoid commitments Monday–Tuesday. Friday carries Lakshmi energy.',
        health: 'Generally stable. Wednesday Rahu Kaal (12:00–01:30 PM) — rest advised.',
        relations: 'Weekend brings warmth. Avoid heated discussions before Wednesday.',
        bestDays: ['Wednesday', 'Thursday'],
        avoidDays: ['Monday'],
        muhurta: 'Best window for new beginnings: Thursday 9:00–10:30 AM.',
      },
    ],
    monthly: [
      {
        month: '2026-02',
        overallTone: 'Mixed',
        majorTransit: 'Saturn deepens transit through 8th from natal Moon. Sade Sati peak begins.',
        dashaInsight: 'Saturn Mahadasha — Mercury Antardasha throughout. Restructuring theme.',
        career: 'Foundational month. Avoid changes; document everything.',
        finance: 'Conservative posture. Build emergency reserve.',
        health: 'Chronic conditions need attention. Annual check-up advised.',
        relations: 'Family elders need time and patience.',
        keyDates: [
          { date: '2026-02-12', note: 'Maghi Purnima — auspicious for charity and ancestor remembrance.' },
          { date: '2026-02-27', note: 'Saturn–Moon square — emotional caution advised.' },
        ],
        muhurta: 'Avoid major undertakings. Continue ongoing work steadily.',
        remedy: 'Hanuman Chalisa daily; black sesame donation on Saturdays.',
      },
      {
        month: '2026-03',
        overallTone: 'Mixed',
        majorTransit: 'Jupiter direct motion brings gradual relief. Saturn pressure persists.',
        dashaInsight: 'Mercury sub-period activates 12th-house themes — introspection and overseas links.',
        career: 'Behind-the-scenes work yields more than visibility-seeking.',
        finance: 'SIPs continue to favour. Property decisions defer to April.',
        health: 'Improvement after the 15th. Continue preventive routines.',
        relations: 'Old friendships rekindle through unexpected channels.',
        keyDates: [
          { date: '2026-03-08', note: 'Holi — favourable for relationship reset and forgiveness.' },
          { date: '2026-03-22', note: 'Jupiter–Sun trine — clarity on long-term goals.' },
        ],
        muhurta: 'Property paperwork prep favoured second half of month.',
        remedy: 'Yellow cloth donation; Guru beej mantra 11 times before sunrise.',
      },
      {
        month: '2026-04',
        overallTone: 'Favourable',
        majorTransit: 'Saturn continues 8th-house transit. Patience required but Jupiter assists.',
        dashaInsight: 'Saturn Mahadasha – Mercury Antardasha. Career restructuring theme throughout.',
        career: 'Second half opens strongly after the 15th. Avoid job changes before that.',
        finance: 'Hold major investments. SIP and recurring savings favoured.',
        health: 'Lower back and digestive system — preventive care recommended.',
        relations: 'Partner communication needs patience in first two weeks.',
        keyDates: [
          { date: '2026-04-12', note: 'Full Moon in Libra — emotional clarity.' },
          { date: '2026-04-27', note: 'New Moon — ideal for setting new intentions.' },
        ],
        muhurta: 'Property or vehicle purchase: after 18th April. Avoid first week.',
        remedy: 'Hanuman Chalisa on Tuesdays and Saturdays throughout the month.',
      },
    ],
  },
  'ASTRO-2026-002': {
    daily: [
      {
        date: '2026-04-26',
        panchang: { tithi: 'Ashtami', nakshatra: 'Bharani', yoga: 'Vyaghata', karana: 'Bava', vara: 'Sunday' },
        moonSign: 'Aries',
        rahuKaal: '04:30 PM – 06:00 PM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Rose',
        luckyNumber: 6,
        luckyDirection: 'South-East',
        dashaInsight: 'Venus–Sun emphasises self-presentation. Personal style matters today.',
        transitAlert: 'Moon in Bharani — fertile creative ground; ideas flow.',
        careerTip: 'Aesthetic and design work shines; revisit your portfolio.',
        financeTip: 'Dhana Yoga supportive — small auspicious purchase favoured.',
        healthTip: 'Kidney support — increase warm fluids.',
        mantra: 'Om Dram Drim Draum Sah Shukraya Namah',
        auspiciousFor: ['Creative expression', 'Self-care', 'Friend gatherings'],
        avoidToday: ['Confrontations', 'Heavy meals at night'],
      },
      {
        date: '2026-04-27',
        panchang: { tithi: 'Navami', nakshatra: 'Krittika', yoga: 'Shubha', karana: 'Balava', vara: 'Monday' },
        moonSign: 'Taurus',
        rahuKaal: '07:30 AM – 09:00 AM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'White',
        luckyNumber: 2,
        luckyDirection: 'North-West',
        dashaInsight: 'Venus dasha lifts communication-led roles; Mercury in 3rd is engaged.',
        transitAlert: 'Moon enters own sign Taurus — emotional steadiness.',
        careerTip: 'Pitch ideas; clients listen well.',
        financeTip: 'Review of overseas links may surface a Jupiter-9 opportunity.',
        healthTip: 'Pranayama before sunset — Venus-friendly routine.',
        mantra: 'Om Som Somaya Namah',
        auspiciousFor: ['Pitching', 'Networking', 'Mentor meetings'],
        avoidToday: ['Speculation', 'Late-night arguments'],
      },
      {
        date: '2026-04-28',
        panchang: { tithi: 'Dashami', nakshatra: 'Rohini', yoga: 'Siddha', karana: 'Bava', vara: 'Tuesday' },
        moonSign: 'Taurus',
        rahuKaal: '03:00 PM – 04:30 PM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Pink',
        luckyNumber: 6,
        luckyDirection: 'South-East',
        dashaInsight: 'Venus–Sun strong in own house. Marriage-related conversations supported.',
        transitAlert: 'Rohini nakshatra — beauty, growth, and stable commitments favoured.',
        careerTip: 'Document creative output; portfolio review favoured.',
        financeTip: 'Avoid speculation; long-term plans win this week.',
        healthTip: 'Stable; gentle skincare and water intake.',
        mantra: 'Om Som Somaya Namah',
        auspiciousFor: ['Engagement talks', 'Creative work', 'Aesthetic decisions'],
        avoidToday: ['Hasty commitments', 'Excessive sweets'],
      },
    ],
    weekly: [
      {
        weekStart: '2026-04-20',
        weekEnd: '2026-04-26',
        overallTone: 'Favourable',
        keyTransit: 'Venus enters its strongest phase of the month. Aesthetic and relational gains.',
        dashaInsight: 'Venus–Sun continues; self-expression and visibility supported.',
        career: 'Portfolio and presentation work shine. Wednesday lands well.',
        finance: 'Dhana Yoga active. Saving plans favourable.',
        health: 'Kidney sensitivity — stay hydrated, reduce salt.',
        relations: 'Romantic Venus aspect Saturday — meaningful conversation likely.',
        bestDays: ['Wednesday', 'Saturday'],
        avoidDays: ['Monday'],
        muhurta: 'Best window: Saturday 10:00–11:30 AM.',
      },
      {
        weekStart: '2026-04-27',
        weekEnd: '2026-05-03',
        overallTone: 'Favourable',
        keyTransit: 'Sun in own sign in 3rd — courage and self-direction emphasised.',
        dashaInsight: 'Venus–Sun nearing handover; consolidate Venus gains.',
        career: 'Marketing and communication peaks Tuesday–Thursday.',
        finance: 'Jupiter in 9th supports overseas earnings; check on remittances.',
        health: 'Venus-balanced; gentle exercise, no extremes.',
        relations: 'Engagement discussions favoured; family blessing-friendly week.',
        bestDays: ['Tuesday', 'Friday'],
        avoidDays: ['Thursday'],
        muhurta: 'Engagement talks: Friday 11:00 AM – 12:30 PM.',
      },
    ],
    monthly: [
      {
        month: '2026-04',
        overallTone: 'Favourable',
        majorTransit: 'Jupiter strengthens 9th-house themes — mentors, overseas, dharma.',
        dashaInsight: 'Venus Mahadasha – Sun Antardasha. Self-expression through work.',
        career: 'Communication-led roles peak. Apply for visible positions.',
        finance: 'Dhana Yoga active; channel into structured savings.',
        health: 'Maintain pranayama; minor kidney sensitivity indicated.',
        relations: 'Marriage prospects strengthen. Compatibility scoring favourable.',
        keyDates: [
          { date: '2026-04-15', note: 'Venus–Jupiter sextile — favourable for proposals.' },
          { date: '2026-04-29', note: 'Mercury aids communication-led decisions.' },
        ],
        muhurta: 'Engagement: 19 Apr or 6 Oct (later in year). Avoid retrograde windows.',
        remedy: 'Friday Lakshmi pooja; sphatik mala for daily mantra japa.',
      },
    ],
  },
  'ASTRO-2026-003': {
    daily: [
      {
        date: '2026-04-26',
        panchang: { tithi: 'Ashtami', nakshatra: 'Bharani', yoga: 'Vyaghata', karana: 'Bava', vara: 'Sunday' },
        moonSign: 'Aries',
        rahuKaal: '04:30 PM – 06:00 PM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Smoky Grey',
        luckyNumber: 4,
        luckyDirection: 'South-West',
        dashaInsight: 'Rahu–Jupiter favours unconventional moves; Jupiter restrains excess.',
        transitAlert: 'Moon in Bharani — intensity in decisions; pause before action.',
        careerTip: 'Strategic thinking favoured over execution today.',
        financeTip: 'Defer all major capital decisions; HIL flag still active.',
        healthTip: 'Inflammation watch — avoid spicy meals.',
        mantra: 'Om Bhram Bhrim Bhraum Sah Rahave Namah',
        auspiciousFor: ['Strategy review', 'Naga remedies', 'Quiet reflection'],
        avoidToday: ['Litigation moves', 'Risky financial commitments'],
      },
      {
        date: '2026-04-27',
        panchang: { tithi: 'Navami', nakshatra: 'Krittika', yoga: 'Shubha', karana: 'Balava', vara: 'Monday' },
        moonSign: 'Taurus',
        rahuKaal: '07:30 AM – 09:00 AM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Indigo',
        luckyNumber: 9,
        luckyDirection: 'South',
        dashaInsight: 'Jupiter Antardasha protective; foreign-themed work prospers.',
        transitAlert: 'Moon enters Taurus — emotional grounding for the week.',
        careerTip: 'Foreign client outreach favoured; cross-border calls land well.',
        financeTip: 'Kala Sarpa — restraint advised on speculative trades.',
        healthTip: 'Mars in 6th supports general vitality; light cardio favoured.',
        mantra: 'Om Gram Grim Graum Sah Gurave Namah',
        auspiciousFor: ['Foreign outreach', 'Documentation', 'Mentor consultation'],
        avoidToday: ['Speculation', 'Court filings'],
      },
      {
        date: '2026-04-28',
        panchang: { tithi: 'Dashami', nakshatra: 'Rohini', yoga: 'Siddha', karana: 'Bava', vara: 'Tuesday' },
        moonSign: 'Taurus',
        rahuKaal: '03:00 PM – 04:30 PM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Saffron',
        luckyNumber: 7,
        luckyDirection: 'North',
        dashaInsight: 'Rahu–Jupiter day — protected ambition; Jupiter steadies Rahu\'s pull.',
        transitAlert: 'Moon in Rohini soothes Kala Sarpa intensity briefly.',
        careerTip: 'Public speaking and 7th-house themes shine.',
        financeTip: 'Sit out today\'s market volatility.',
        healthTip: 'Watch evening fatigue; early sleep recommended.',
        mantra: 'Om Bhram Bhrim Bhraum Sah Rahave Namah',
        auspiciousFor: ['Public speaking', 'Naga puja', 'Foreign correspondence'],
        avoidToday: ['Major investments', 'Litigation steps'],
      },
    ],
    weekly: [
      {
        weekStart: '2026-04-20',
        weekEnd: '2026-04-26',
        overallTone: 'Challenging',
        keyTransit: 'Kala Sarpa intensification mid-week. Caution mode.',
        dashaInsight: 'Rahu–Jupiter under pressure; Jupiter\'s grace remains the protector.',
        career: 'Hold ambitious moves; consolidate existing relationships.',
        finance: 'Two flagged sections active — defer all capital decisions.',
        health: 'Inflammation risk; soothing routines favoured.',
        relations: '7th-house stellium activated; partner communication critical.',
        bestDays: ['Friday'],
        avoidDays: ['Tuesday', 'Wednesday'],
        muhurta: 'Avoid muhurta-dependent action this week.',
      },
      {
        weekStart: '2026-04-27',
        weekEnd: '2026-05-03',
        overallTone: 'Mixed',
        keyTransit: 'Jupiter aspects ease early-week pressure; Rahu\'s urge tempered.',
        dashaInsight: 'Restraint is the watchword. Foreign matters supported.',
        career: 'Quiet leadership favoured. Let Jupiter\'s wisdom show.',
        finance: 'Naga remedies recommended; await Jyotishi sign-off on flagged sections.',
        health: 'Stable mid-week; weekend rest important.',
        relations: 'Heart-to-heart conversations favoured.',
        bestDays: ['Wednesday', 'Saturday'],
        avoidDays: ['Tuesday'],
        muhurta: 'Filing or formal letters: Saturday 10:00–11:00 AM only after Jyotishi review.',
      },
    ],
    monthly: [
      {
        month: '2026-04',
        overallTone: 'Challenging',
        majorTransit: 'Kala Sarpa active. Saturn aspects amplify caution themes.',
        dashaInsight: 'Rahu Mahadasha – Jupiter Antardasha. Restraint with quiet ambition.',
        career: 'Foreign and unconventional arcs favoured; existing leadership stable.',
        finance: 'HIGH CAUTION month. Restraint over speculation. Two HIL flags currently.',
        health: 'Mars in 6th holds vitality; watch inflammation Apr–May.',
        relations: '7th-house themes engaged; communication breakthroughs available.',
        keyDates: [
          { date: '2026-04-08', note: 'Best filing window opens — pending Jyotishi sign-off.' },
          { date: '2026-04-21', note: 'Court proceedings favour calm presentation.' },
        ],
        muhurta: 'Pending Jyotishi review on litigation timing.',
        remedy: 'Naga pratishtha; silver Naga idol gifted to temple; Rahu shanti homa once.',
      },
    ],
  },
  'ASTRO-2026-004': {
    daily: [
      {
        date: '2026-04-26',
        panchang: { tithi: 'Ashtami', nakshatra: 'Bharani', yoga: 'Vyaghata', karana: 'Bava', vara: 'Sunday' },
        moonSign: 'Aries',
        rahuKaal: '04:30 PM – 06:00 PM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Gold',
        luckyNumber: 1,
        luckyDirection: 'East',
        dashaInsight: 'Jupiter–Saturn favours research and academic depth.',
        transitAlert: 'Sun in own house aspect — confidence and clarity strong.',
        careerTip: 'PhD application drafts shine today.',
        financeTip: 'Saturn in 11th supports steady income; scholarship search favoured.',
        healthTip: 'Eye care — reduce screen time after sunset.',
        mantra: 'Om Hram Hrim Hraum Sah Suryaya Namah',
        auspiciousFor: ['Application drafting', 'Mentor calls', 'Scholarship research'],
        avoidToday: ['Late-night studying', 'Skipping meals'],
      },
      {
        date: '2026-04-27',
        panchang: { tithi: 'Navami', nakshatra: 'Krittika', yoga: 'Shubha', karana: 'Balava', vara: 'Monday' },
        moonSign: 'Taurus',
        rahuKaal: '07:30 AM – 09:00 AM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Yellow',
        luckyNumber: 3,
        luckyDirection: 'North-East',
        dashaInsight: 'Jupiter day amplifies the Mahadasha — academic aspirations supported.',
        transitAlert: 'Moon in Taurus brings emotional steadiness for focused study.',
        careerTip: 'Long writing or research session lands well.',
        financeTip: 'Apply for foreign scholarships now; Jupiter favours.',
        healthTip: 'Strong constitution; maintain Surya Namaskar habit.',
        mantra: 'Om Gram Grim Graum Sah Gurave Namah',
        auspiciousFor: ['Application work', 'Research', 'Mentor meetings'],
        avoidToday: ['Distractions', 'Procrastination'],
      },
      {
        date: '2026-04-28',
        panchang: { tithi: 'Dashami', nakshatra: 'Rohini', yoga: 'Siddha', karana: 'Bava', vara: 'Tuesday' },
        moonSign: 'Taurus',
        rahuKaal: '03:00 PM – 04:30 PM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Cream',
        luckyNumber: 5,
        luckyDirection: 'North',
        dashaInsight: 'Saturn Antardasha lends discipline — long-form work favoured.',
        transitAlert: 'Rohini nakshatra — favourable for new commitments.',
        careerTip: 'Submit applications drafted earlier; momentum supports.',
        financeTip: 'Track recurring scholarship deadlines this week.',
        healthTip: 'Eye relaxation breaks every 45 minutes.',
        mantra: 'Om Sham Shanaischaraya Namah',
        auspiciousFor: ['Submitting applications', 'Long study sessions', 'Visa prep'],
        avoidToday: ['Impulsive program switches', 'Late-night caffeine'],
      },
    ],
    weekly: [
      {
        weekStart: '2026-04-20',
        weekEnd: '2026-04-26',
        overallTone: 'Favourable',
        keyTransit: 'Jupiter–Sun trine supports academic confidence.',
        dashaInsight: 'Jupiter–Saturn rewards consistent effort.',
        career: 'Research week. Wednesday best for committee meetings.',
        finance: 'Scholarship applications — apply by Friday.',
        health: 'Stable; eye care priority.',
        relations: 'Long-distance connection deepens by weekend.',
        bestDays: ['Wednesday', 'Thursday'],
        avoidDays: ['Saturday'],
        muhurta: 'Application submission: Thursday 10:00–11:00 AM.',
      },
      {
        weekStart: '2026-04-27',
        weekEnd: '2026-05-03',
        overallTone: 'Favourable',
        keyTransit: 'Sun in own sign supports academic visibility.',
        dashaInsight: 'Saturn Antardasha steadies long-form work.',
        career: 'Submit applications, prep for interviews.',
        finance: 'Scholarship interview coaching favoured.',
        health: 'Strong constitution; maintain pranayama.',
        relations: 'Mentor relationships strengthen.',
        bestDays: ['Tuesday', 'Thursday'],
        avoidDays: ['Saturday'],
        muhurta: 'Visa interview muhurta: Thursday morning hours.',
      },
    ],
    monthly: [
      {
        month: '2026-04',
        overallTone: 'Favourable',
        majorTransit: 'Jupiter strong in 9th — overseas education themes peaked.',
        dashaInsight: 'Jupiter Mahadasha – Saturn Antardasha. Academic foundation.',
        career: 'PhD or specialist track strongly indicated this month.',
        finance: 'Scholarships and grants available through March 2027.',
        health: 'Robust; eye health priority during Mercury sub-periods.',
        relations: 'Long-distance connection forming late 2026 begins to warm.',
        keyDates: [
          { date: '2026-04-17', note: 'Application window 1 — foreign universities.' },
          { date: '2026-04-30', note: 'Mentor meeting auspicious for endorsement letters.' },
        ],
        muhurta: 'Visa interview: morning hours, Thursdays.',
        remedy: 'Surya Namaskar at sunrise; Ganesha mantra before exams.',
      },
    ],
  },
  'ASTRO-2026-005': {
    daily: [
      {
        date: '2026-04-26',
        panchang: { tithi: 'Ashtami', nakshatra: 'Bharani', yoga: 'Vyaghata', karana: 'Bava', vara: 'Sunday' },
        moonSign: 'Aries',
        rahuKaal: '04:30 PM – 06:00 PM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Coral',
        luckyNumber: 5,
        luckyDirection: 'North',
        dashaInsight: 'Mercury–Venus favours business expansion conversations.',
        transitAlert: 'Sun supports authority; partner discussions favoured.',
        careerTip: 'Schedule strategy session for Wednesday.',
        financeTip: 'Lakshmi Yoga — property research auspicious.',
        healthTip: 'Joint care — gentle stretching morning routine.',
        mantra: 'Om Bram Brim Braum Sah Budhaya Namah',
        auspiciousFor: ['Business strategy', 'Family time', 'Property research'],
        avoidToday: ['Solo travel', 'Heavy lifting'],
      },
      {
        date: '2026-04-27',
        panchang: { tithi: 'Navami', nakshatra: 'Krittika', yoga: 'Shubha', karana: 'Balava', vara: 'Monday' },
        moonSign: 'Taurus',
        rahuKaal: '07:30 AM – 09:00 AM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Green',
        luckyNumber: 5,
        luckyDirection: 'North',
        dashaInsight: 'Mercury day amplifies the Mahadasha — communications shine.',
        transitAlert: 'Moon in Taurus — favourable for property reviews.',
        careerTip: 'Draft business agreements; finalise on Wednesday.',
        financeTip: 'Land or commercial property search favoured.',
        healthTip: 'Mars in 8th — avoid risky sports.',
        mantra: 'Om Bram Brim Braum Sah Budhaya Namah',
        auspiciousFor: ['Drafting agreements', 'Property visits', 'Children\'s academic talks'],
        avoidToday: ['Risky travel', 'Loud confrontations'],
      },
      {
        date: '2026-04-28',
        panchang: { tithi: 'Dashami', nakshatra: 'Rohini', yoga: 'Siddha', karana: 'Bava', vara: 'Tuesday' },
        moonSign: 'Taurus',
        rahuKaal: '03:00 PM – 04:30 PM',
        abhijitMuhurta: '12:08 PM – 12:56 PM',
        luckyColour: 'Maroon',
        luckyNumber: 9,
        luckyDirection: 'South',
        dashaInsight: 'Venus Antardasha lifts partnerships and aesthetic decisions.',
        transitAlert: 'Rohini brings stable, growth-oriented decisions.',
        careerTip: 'Q3 product launch planning aligns now.',
        financeTip: 'Lakshmi Yoga active — auspicious property registration window.',
        healthTip: 'Mangal Dosha calmed via Hanuman Chalisa.',
        mantra: 'Om Hanumate Namah',
        auspiciousFor: ['Property registration', 'Partnership signing', 'Family decisions'],
        avoidToday: ['Disputes', 'Risky travel'],
      },
    ],
    weekly: [
      {
        weekStart: '2026-04-20',
        weekEnd: '2026-04-26',
        overallTone: 'Favourable',
        keyTransit: 'Venus enters strong phase — partnership and property themes peak.',
        dashaInsight: 'Mercury–Venus week supports business and asset decisions.',
        career: 'Strategy week; finalise Q3 plans.',
        finance: 'Property visits auspicious; land or commercial preferred.',
        health: 'Watch joints; preventive care.',
        relations: 'Children\'s academic discussions favoured.',
        bestDays: ['Wednesday', 'Thursday'],
        avoidDays: ['Tuesday'],
        muhurta: 'Property registration: Saturday 10:00–11:30 AM.',
      },
      {
        weekStart: '2026-04-27',
        weekEnd: '2026-05-03',
        overallTone: 'Favourable',
        keyTransit: 'Lakshmi Yoga energised; Mercury sharpens decisions.',
        dashaInsight: 'Mercury–Venus continues; partnerships consolidate.',
        career: 'Sign business agreements; team expansion favoured.',
        finance: 'Property registration window opens after the 28th.',
        health: 'Stable; gentle morning routine.',
        relations: 'Eldest child\'s academic phase needs encouragement.',
        bestDays: ['Wednesday', 'Thursday'],
        avoidDays: ['Tuesday'],
        muhurta: 'Business agreements: Wednesday or Thursday morning.',
      },
    ],
    monthly: [
      {
        month: '2026-04',
        overallTone: 'Favourable',
        majorTransit: 'Lakshmi Yoga active — wealth themes peak.',
        dashaInsight: 'Mercury Mahadasha – Venus Antardasha. Business expansion supported.',
        career: 'Q3 2026 favourable for product launch; build pipeline this month.',
        finance: 'Property acquisition window Jun–Sep 2026 — research now.',
        health: 'Joint health — preventive care; cautious during travel.',
        relations: 'Children\'s career trajectory strong; eldest entering pivotal phase.',
        keyDates: [
          { date: '2026-04-14', note: 'Property registration auspicious window.' },
          { date: '2026-04-28', note: 'Wed/Thu mornings best for business agreements.' },
        ],
        muhurta: 'Property registration: 14 Jun, 22 Aug 2026; agreements Wed/Thu mornings.',
        remedy: 'Mangal shanti puja annually; coral ring on Tuesday in gold; Hanuman Chalisa Tue/Sat.',
      },
    ],
  },
};
