// Central mock data for 5 consultations.
// Houses are 1..12. Planet abbreviations: Su Mo Ma Me Ju Ve Sa Ra Ke. Lg = Lagna marker.

function makeLog(rows) {
  const base = new Date('2026-04-28T09:14:32');
  return rows.map((r, i) => {
    const t = new Date(base.getTime() + i * 7400 + (i % 3) * 1700);
    const hh = String(t.getHours()).padStart(2, '0');
    const mm = String(t.getMinutes()).padStart(2, '0');
    const ss = String(t.getSeconds()).padStart(2, '0');
    return { time: `${hh}:${mm}:${ss}`, type: r[0], message: r[1] };
  });
}

export const MOCK_DATA = [
  {
    id: 'ASTRO-2026-001',
    name: 'Arjun Sharma',
    email: 'arjun.sharma@email.com',
    receivedAt: '2026-04-28 09:14:32',
    waitingMin: 14,
    status: 'HIL_PENDING',
    dob: '15 July 1990',
    tob: '06:32 AM',
    pob: 'Mumbai, Maharashtra',
    coordinates: '18.97°N 72.82°E',
    timezone: 'UTC+5:30',
    ayanamsa: 'Lahiri',
    lagna: 'Cancer',
    rasiChart: {
      1: ['Lg', 'Mo'],
      4: ['Ma'],
      5: ['Ra'],
      7: ['Ve'],
      10: ['Ju', 'Su'],
      11: ['Ke', 'Sa'],
      12: ['Me'],
    },
    activeMahadasha: 'Saturn',
    activeAntardasha: 'Mercury',
    dashaEnds: 'March 2028',
    yogas: ['Raj Yoga', 'Gajakesari Yoga'],
    doshas: ['Sade Sati', 'Mangal Dosha'],
    concerns: ['Career', 'Finance', 'Health'],
    overallConfidence: 72,
    processingTime: '00:02:34',
    interpretations: {
      career: { insight: 'Saturn–Mercury dasha favours methodical career building. Promotion window opens Aug–Nov 2026 if you stay in current role; a lateral move now would forfeit Jupiter\'s 10th-house dignity.', confidence: 85, planet: 'Saturn', flagged: false },
      finance: { insight: 'Jupiter in 10th from Lagna activates 2nd-house wealth. Long-term investments preferred over speculation. Avoid major capital lock-ups during Mercury sub-period retrogrades.', confidence: 78, planet: 'Jupiter', flagged: false },
      health: { insight: 'Saturn currently transiting natal 8th house — chronic stress markers indicated. Lower back and digestive system require attention. Recommend medical screening within 90 days.', confidence: 45, planet: 'Saturn', flagged: true, flagReason: 'Saturn transiting 8th house — sensitive health prediction. Confidence below 50% threshold for autonomous clearance.' },
      relations: { insight: 'Venus in 7th brings stable partnership energy through 2027. Existing relationships strengthen; for unmarried, Nov 2026 carries strong matrimonial yoga.', confidence: 81, planet: 'Venus', flagged: false },
      muhurta: { insight: 'Best dates for new ventures: 12 May, 27 June, 14 September 2026. Avoid Tuesdays in July (Mangal Dosha activation). Pradosh Kaal favourable.', confidence: 88, planet: 'Jupiter', flagged: false },
    },
    hilStatus: 'PENDING',
    remedy: 'Recite Hanuman Chalisa daily at sunrise. Donate black sesame seeds on Saturdays. Wear blue sapphire only after trial period of 3 days.',
    reportReady: false,
    agentLog: makeLog([
      ['INFO',      'Inbound consultation received via email gateway.'],
      ['INFO',      'Parsing birth data: DOB=15 July 1990, TOB=06:32 AM, POB=Mumbai, Maharashtra.'],
      ['INFO',      'Geocoding birth location Mumbai, Maharashtra...'],
      ['SUCCESS',   'Coordinates locked: 18.97°N 72.82°E UTC+5:30. Lahiri Ayanamsa applied.'],
      ['INFO',      'Swiss Ephemeris v2.10 initialised. Calculating planetary positions for 15 July 1990 06:32 AM IST...'],
      ['SUCCESS',   'Lagna confirmed: Cancer. Moon in 1st house, strong positional strength (Shadbala 6.4/8).'],
      ['SUCCESS',   'Raj Yoga detected — Jupiter conjunct Sun in 10th house from Lagna. Confidence: HIGH.'],
      ['SUCCESS',   'Gajakesari Yoga detected — Jupiter–Moon kendra relationship. Confidence: HIGH.'],
      ['WARNING',   'Sade Sati ongoing — Saturn in 12th from natal Moon. Phase: peak. Duration remaining ~22 months.'],
      ['WARNING',   'Mangal Dosha confirmed — Mars in 4th house. Strength: moderate.'],
      ['INFO',      'Calculating Vimshottari Dasha. Active: Saturn Mahadasha → Mercury Antardasha. Ends Mar 2028.'],
      ['INFO',      'Generating interpretation for concern: Career.'],
      ['SUCCESS',   'Career insight cleared — confidence 85%.'],
      ['INFO',      'Generating interpretation for concern: Finance.'],
      ['SUCCESS',   'Finance insight cleared — confidence 78%.'],
      ['INFO',      'Generating interpretation for concern: Health.'],
      ['FLAGGED',   'FLAGGED: Saturn transiting natal 8th house. Health prediction sensitivity threshold exceeded.'],
      ['ESCALATED', 'Routing health interpretation to HIL review queue. Awaiting human astrologer.'],
      ['SUCCESS',   'Relations insight cleared — confidence 81%.'],
      ['SUCCESS',   'Muhurta calculation complete — confidence 88%.'],
      ['INFO',      'Compiling remedy recommendations from Parashara corpus and regional traditions.'],
      ['INFO',      '4 of 5 sections auto-cleared. 1 awaiting HIL.'],
    ]),
  },
  {
    id: 'ASTRO-2026-002',
    name: 'Priya Iyer',
    email: 'priya.iyer@email.com',
    receivedAt: '2026-04-28 09:42:08',
    waitingMin: 0,
    status: 'PROCESSING',
    dob: '03 February 1988',
    tob: '11:48 PM',
    pob: 'Chennai, Tamil Nadu',
    coordinates: '13.08°N 80.27°E',
    timezone: 'UTC+5:30',
    ayanamsa: 'Lahiri',
    lagna: 'Libra',
    rasiChart: {
      1: ['Lg'],
      2: ['Ve'],
      3: ['Su', 'Me'],
      4: ['Ma'],
      6: ['Ra'],
      9: ['Ju'],
      10: ['Mo'],
      12: ['Sa', 'Ke'],
    },
    activeMahadasha: 'Venus',
    activeAntardasha: 'Sun',
    dashaEnds: 'February 2027',
    yogas: ['Dhana Yoga'],
    doshas: [],
    concerns: ['Marriage', 'Career'],
    overallConfidence: 81,
    processingTime: '00:01:12',
    interpretations: {
      career: { insight: 'Venus dasha currently elevating creative and aesthetic professions. Mercury in 3rd house supports communication-led roles.', confidence: 84, planet: 'Venus', flagged: false },
      finance: { insight: 'Dhana Yoga active through 2027. Jupiter in 9th supports wealth via mentors and overseas connections.', confidence: 80, planet: 'Jupiter', flagged: false },
      health: { insight: 'No major affliction. Maintain regular Pranayama; minor kidney sensitivity indicated.', confidence: 76, planet: 'Venus', flagged: false },
      relations: { insight: 'Marriage prospects strong from Sep 2026. Partner likely from professional or academic circle. Compatibility scoring favourable.', confidence: 83, planet: 'Venus', flagged: false },
      muhurta: { insight: 'Engagement muhurta auspicious: 6 Oct, 19 Nov 2026. Avoid Mercury retrograde windows.', confidence: 82, planet: 'Jupiter', flagged: false },
    },
    hilStatus: 'NONE',
    remedy: 'Friday Lakshmi pooja. White cloth donation at temple. Sphatik mala for daily mantra japa.',
    reportReady: false,
    agentLog: makeLog([
      ['INFO',    'Inbound consultation received.'],
      ['INFO',    'Parsing birth data: DOB=03 Feb 1988, TOB=11:48 PM, POB=Chennai.'],
      ['SUCCESS', 'Coordinates locked: 13.08°N 80.27°E. Lahiri Ayanamsa applied.'],
      ['INFO',    'Swiss Ephemeris calculating planetary positions...'],
      ['SUCCESS', 'Lagna confirmed: Libra. No malefic in 1st house.'],
      ['SUCCESS', 'Dhana Yoga detected — 2nd lord Mars in own sign aspecting 11th.'],
      ['INFO',    'Vimshottari: Venus Mahadasha → Sun Antardasha. Ends Feb 2027.'],
      ['INFO',    'Generating interpretations for Marriage and Career...'],
    ]),
  },
  {
    id: 'ASTRO-2026-003',
    name: 'Rahul Mehta',
    email: 'rahul.mehta@email.com',
    receivedAt: '2026-04-28 08:51:17',
    waitingMin: 38,
    status: 'HIL_PENDING',
    dob: '22 November 1979',
    tob: '03:18 PM',
    pob: 'Ahmedabad, Gujarat',
    coordinates: '23.02°N 72.57°E',
    timezone: 'UTC+5:30',
    ayanamsa: 'Lahiri',
    lagna: 'Pisces',
    rasiChart: {
      1: ['Lg', 'Ju'],
      3: ['Ke'],
      4: ['Sa'],
      6: ['Ma'],
      7: ['Su', 'Me', 'Ve'],
      9: ['Ra'],
      11: ['Mo'],
    },
    activeMahadasha: 'Rahu',
    activeAntardasha: 'Jupiter',
    dashaEnds: 'July 2029',
    yogas: ['Hamsa Yoga', 'Budha-Aditya Yoga'],
    doshas: ['Kala Sarpa Dosha'],
    concerns: ['Litigation', 'Health', 'Finance'],
    overallConfidence: 64,
    processingTime: '00:03:41',
    interpretations: {
      career: { insight: 'Rahu–Jupiter dasha amplifies foreign or unconventional career arcs. Existing leadership role stable through 2027.', confidence: 76, planet: 'Rahu', flagged: false },
      finance: { insight: 'Significant capital decision indicated within 6 months. Jupiter in Lagna provides protection but Rahu adds speculative pull — restraint advised.', confidence: 58, planet: 'Jupiter', flagged: true, flagReason: 'Kala Sarpa Dosha active. Financial prediction with material consequence — HIL review mandatory.' },
      health: { insight: 'Mars in 6th house supports general vitality. Watch for inflammatory conditions during Apr–May 2027.', confidence: 71, planet: 'Mars', flagged: false },
      relations: { insight: '7th house stellium (Sun, Mercury, Venus) keeps partnership central. Communication breakthroughs expected.', confidence: 79, planet: 'Venus', flagged: false },
      muhurta: { insight: 'Pending litigation: best filing windows 8 May, 21 June 2026. Court proceedings favour calm presentation.', confidence: 42, planet: 'Saturn', flagged: true, flagReason: 'Litigation timing prediction crosses legal-impact threshold. Confidence below 50%.' },
    },
    hilStatus: 'PENDING',
    remedy: 'Naga pratishtha at Nageshwar Jyotirlinga. Silver Naga idol gifted to temple. Rahu shanti homa once.',
    reportReady: false,
    agentLog: makeLog([
      ['INFO',      'Inbound consultation received.'],
      ['SUCCESS',   'Coordinates locked: 23.02°N 72.57°E. Lahiri Ayanamsa applied.'],
      ['SUCCESS',   'Lagna confirmed: Pisces. Jupiter in own sign in 1st house — strong.'],
      ['SUCCESS',   'Hamsa Yoga detected — Jupiter exalted in Lagna kendra.'],
      ['SUCCESS',   'Budha-Aditya Yoga detected — Mercury and Sun conjunct in 7th house.'],
      ['WARNING',   'Kala Sarpa Dosha confirmed — all planets between Rahu (9H) and Ketu (3H).'],
      ['INFO',      'Vimshottari: Rahu Mahadasha → Jupiter Antardasha. Ends Jul 2029.'],
      ['FLAGGED',   'FLAGGED: Finance interpretation involves material capital decision. Confidence 58% — below auto-clear threshold.'],
      ['FLAGGED',   'FLAGGED: Litigation muhurta below 50% confidence under Kala Sarpa influence.'],
      ['ESCALATED', 'Routing 2 sections to HIL queue.'],
      ['INFO',      'Career, Health, Relations sections cleared autonomously.'],
    ]),
  },
  {
    id: 'ASTRO-2026-004',
    name: 'Nisha Reddy',
    email: 'nisha.reddy@email.com',
    receivedAt: '2026-04-28 07:22:54',
    waitingMin: 0,
    status: 'INTERPRETING',
    dob: '09 September 1995',
    tob: '04:55 AM',
    pob: 'Hyderabad, Telangana',
    coordinates: '17.38°N 78.49°E',
    timezone: 'UTC+5:30',
    ayanamsa: 'Lahiri',
    lagna: 'Leo',
    rasiChart: {
      1: ['Lg', 'Su'],
      2: ['Me'],
      3: ['Ve'],
      4: ['Ma', 'Ke'],
      7: ['Mo'],
      9: ['Ju'],
      10: ['Ra'],
      11: ['Sa'],
    },
    activeMahadasha: 'Jupiter',
    activeAntardasha: 'Saturn',
    dashaEnds: 'November 2031',
    yogas: ['Sasa Yoga', 'Chandra Mangal Yoga'],
    doshas: [],
    concerns: ['Higher Studies', 'Career'],
    overallConfidence: 86,
    processingTime: '00:02:08',
    interpretations: {
      career: { insight: 'Jupiter–Saturn dasha favours academic and research-oriented paths. PhD or specialist track strongly indicated.', confidence: 89, planet: 'Jupiter', flagged: false },
      finance: { insight: 'Saturn in 11th house ensures steady income growth. Scholarships and grants available through Mar 2027.', confidence: 87, planet: 'Saturn', flagged: false },
      health: { insight: 'Sun in Lagna provides robust constitution. Maintain eye health; reduce screen time during Mercury sub-periods.', confidence: 84, planet: 'Sun', flagged: false },
      relations: { insight: 'Moon in 7th brings emotionally rich partnerships. Long-distance connection forming late 2026.', confidence: 82, planet: 'Moon', flagged: false },
      muhurta: { insight: 'Application windows for foreign universities: 17 Aug, 4 Oct 2026. Visa interview muhurta: morning hours, Thursdays.', confidence: 88, planet: 'Jupiter', flagged: false },
    },
    hilStatus: 'NONE',
    remedy: 'Surya Namaskar at sunrise. Yellow sapphire after consultation with Jyotishi. Ganesha mantra before exams.',
    reportReady: false,
    agentLog: makeLog([
      ['INFO',    'Inbound consultation received.'],
      ['SUCCESS', 'Coordinates locked: 17.38°N 78.49°E. Lahiri Ayanamsa applied.'],
      ['SUCCESS', 'Lagna confirmed: Leo. Sun in own sign in 1st house — very strong.'],
      ['SUCCESS', 'Sasa Yoga detected — Saturn in own sign in kendra from Moon.'],
      ['SUCCESS', 'Chandra Mangal Yoga — Moon and Mars mutual aspect.'],
      ['INFO',    'Vimshottari: Jupiter Mahadasha → Saturn Antardasha. Ends Nov 2031.'],
      ['INFO',    'Generating interpretations for Higher Studies and Career...'],
      ['SUCCESS', 'Career interpretation cleared — confidence 89%.'],
      ['INFO',    'Compiling remedy recommendations...'],
    ]),
  },
  {
    id: 'ASTRO-2026-005',
    name: 'Vikram Singh',
    email: 'vikram.singh@email.com',
    receivedAt: '2026-04-27 18:09:41',
    waitingMin: 0,
    status: 'COMPLETE',
    dob: '28 May 1972',
    tob: '09:14 AM',
    pob: 'Jaipur, Rajasthan',
    coordinates: '26.91°N 75.79°E',
    timezone: 'UTC+5:30',
    ayanamsa: 'Lahiri',
    lagna: 'Gemini',
    rasiChart: {
      1: ['Lg', 'Me'],
      3: ['Mo'],
      5: ['Ra'],
      6: ['Sa'],
      8: ['Ma'],
      10: ['Ju', 'Ve'],
      11: ['Ke', 'Su'],
    },
    activeMahadasha: 'Mercury',
    activeAntardasha: 'Venus',
    dashaEnds: 'June 2030',
    yogas: ['Bhadra Yoga', 'Lakshmi Yoga'],
    doshas: ['Mangal Dosha'],
    concerns: ['Business', 'Property', 'Children'],
    overallConfidence: 79,
    processingTime: '00:02:53',
    interpretations: {
      career: { insight: 'Mercury–Venus dasha excellent for business expansion and new partnerships. Q3 2026 favourable for product launch.', confidence: 82, planet: 'Mercury', flagged: false },
      finance: { insight: 'Lakshmi Yoga active. Property acquisition window Jun–Sep 2026. Land or commercial real estate preferred over residential.', confidence: 81, planet: 'Venus', flagged: false },
      health: { insight: 'Mars in 8th house — exercise caution during travel. Joint health needs preventive care.', confidence: 73, planet: 'Mars', flagged: false },
      relations: { insight: 'Children\'s career trajectory strong; eldest entering pivotal academic phase.', confidence: 78, planet: 'Jupiter', flagged: false },
      muhurta: { insight: 'Property registration auspicious: 14 Jun, 22 Aug 2026. Business agreement signing best Wed/Thu mornings.', confidence: 80, planet: 'Mercury', flagged: false },
    },
    hilStatus: 'APPROVED',
    remedy: 'Mangal shanti puja annually. Coral ring on Tuesday in gold. Hanuman Chalisa Tuesdays/Saturdays.',
    reportReady: true,
    agentLog: makeLog([
      ['INFO',    'Inbound consultation received.'],
      ['SUCCESS', 'Coordinates locked: 26.91°N 75.79°E.'],
      ['SUCCESS', 'Lagna confirmed: Gemini. Mercury in own sign in 1st house.'],
      ['SUCCESS', 'Bhadra Yoga detected — Mercury in kendra in own sign.'],
      ['SUCCESS', 'Lakshmi Yoga — 9th lord Saturn well-placed; Venus in 10th.'],
      ['WARNING', 'Mangal Dosha — Mars in 8th house. Mitigation factors present.'],
      ['INFO',    'All 5 interpretations generated.'],
      ['SUCCESS', 'All sections auto-cleared. Confidence > threshold.'],
      ['SUCCESS', 'HIL spot-check approved by astrologer Pt. R. Joshi.'],
      ['SUCCESS', 'Final report compiled and delivered. Email sent at 21:14 IST.'],
    ]),
  },
];

export const STATUS_META = {
  PROCESSING:   { label: 'Processing',   tone: 'blue',    bg: 'var(--blue-50)',    fg: '#1D4ED8' },
  INTERPRETING: { label: 'Interpreting', tone: 'indigo',  bg: 'var(--indigo-50)',  fg: 'var(--indigo-700)' },
  HIL_PENDING:  { label: 'HIL Pending',  tone: 'amber',   bg: 'var(--amber-50)',   fg: 'var(--amber-700)' },
  COMPLETE:     { label: 'Complete',     tone: 'emerald', bg: 'var(--emerald-50)', fg: 'var(--emerald-700)' },
};

export const PIPELINE_STEPS = [
  'Data Received',
  'Validated',
  'Charts Generated',
  'Interpreted',
  'HIL Review',
  'Report Ready',
  'Delivered',
];

export function pipelineProgress(c) {
  if (c.status === 'PROCESSING') return 1;
  if (c.status === 'INTERPRETING') return 3;
  if (c.status === 'HIL_PENDING') return 4;
  if (c.status === 'COMPLETE') return c.reportReady ? 6 : 5;
  return 0;
}
